### ISSUE TITLE
Mirror the structure of the content folder with paths served

### ISSUE THREAD

**Issue by saffaffi** [gememma/wirebrush#35]
In #31, I suggested that for the time being, you should just serve the files from the top level of your content folder in a flat structure on top level paths, e.g. `GET /foo`, `GET /bar`, `GET /baz`, and ignore any subfolders.

Now, flesh out that handling of the contents of the folder so that its structure is mirrored in the paths you serve on your web server. Also, treat any file with the name `_index.md` as representing the page for the folder it lives in. In other words, the following file structure...

```console
$ exa -aT content
content
├── _index.md
├── about.md
└── blog
   ├── _index.md
   ├── how-to-write-website.md
   └── i-ate-3009-cinnamon-rolls.md
```

...would make the five markdown files' contents available at the following paths, in order:

- `GET /`
- `GET /about`
- `GET /blog`
- `GET /blog/how-to-write-website`
- `GET /blog/i-ate-3009-cinnamon-rolls`

**Comment by gememma** [comment]
Since I don't have any intention of having "posts" on my website, I do not think this feature is necessary :)
