### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by gememma** [gememma/wirebrush#38]
Add the favicon to show on tabs with the website open by creating an image assets folder

**Comment by gememma** [comment]
@saffaffi I can't exactly work out how to "serve" the favicon in a way that the browser understands - is it similar to how the stylesheet is served at a specific path?

**Comment by saffaffi** [comment]
Yes, it's extremely similar to a stylesheet. There are two parts to the process (again, just like the stylesheet):

- You need to serve the file(s) at specific paths (such as `/favicon.ico`, and others for various sizes of icon for specific platforms and use-cases)
- You need to provide the appropriate `<link>` tags in your HTML header on every page.

You can probably get complete sets of both of those things from an online favicon generator! They tend to be able to take an image that you provide and scale it to all the appropriate sizes and file formats, and spit them back out alongside some HTML that you can use in your header.
