### ISSUE TITLE
Add homepage content

### ISSUE THREAD

**Issue by gememma** [gememma/wirebrush#45]
Add content to the homepage including links to other pages

**Comment by gememma** [comment]
@saffaffi what is your recemmendation for where to put the homepage content? I can think of a couple options:

1. Have a home.md file somewhere other than the static directory
2. Have a home.md file in the static dir, and auto redirect from gemmat.dev -> gemmat.dev/home
3. Have the page content as HTML hardcoded into the handler module's `hello()` function
4. Have the page content as HTML hardcoded somewhere other than the handler module
5. Some combination of the above

**Comment by saffaffi** [comment]
I think I'd opt for `1`, or a variation of it. The way that a static site handler would typically handle this would be to put it in `content/_index.md` - and you could certainly do that if you wanted to!
